version: 2.1
orbs:
  ruby: cimg/ruby@1.1.2
jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
